### ISSUE TITLE
Add a background gradient or graphic

### ISSUE THREAD

**Issue by Namanbhatia7** [Namanbhatia7/False9#13]
Add a decent background gradient or design a graphic that could be used in all pages.

**Comment by m4tr1k** [comment]
@Namanbhatia7 Hi! can I take this one?

**Comment by KeerthanaHK** [comment]
Hi, Can I do this please?

**Comment by Namanbhatia7** [comment]
![723bf-15980841315808](https://user-images.githubusercontent.com/52316491/94852394-74945780-0447-11eb-8454-38dd38f6cebb.jpg)

**Comment by Namanbhatia7** [comment]
@m4tr1k @KeerthanaHK  Please go ahead. I am looking for your PR
I have attached  a sample design in the comment above. I want to have a classic background design that could be used in all pages with some color difference :)
