### ISSUE TITLE
Add Sections to home page

### ISSUE THREAD

**Issue by Namanbhatia7** [Namanbhatia7/False9#16]
Add footer to home page

**Comment by Kapersky1337** [comment]
Please assign this to me, I'll be working on this.

**Comment by priyankaagrawal123** [comment]
I am interested. I can implement.
Please assign this issue to me.

**Comment by Ayushgup85** [comment]
Can i work on this issue?

**Comment by Namanbhatia7** [comment]
@Ayushgup85 Sure, go head

**Comment by Aps1177** [comment]
I want to work on this issue . Please assign
