### ISSUE TITLE
Top Scorers Display

### ISSUE THREAD

**Issue by Namanbhatia7** [Namanbhatia7/False9#21]
Right now top scorers of leagues are displayed in table format. Redesign the format into full-width cards

**Comment by riyakalra** [comment]
Please assign this issue to me.

**Comment by NikhilSharmaWe** [comment]
looking forward to work on this issue

**Comment by Namanbhatia7** [comment]
> looking forward to work on this issue

Hey Nikhil, Sorry for late reply.
This issue has already been resolved. However, you can work on similar issue.
Make Standings table similar to top scorers table. If you are interested you can go ahead.
