### ISSUE TITLE
Live Matches route

### ISSUE THREAD

**Issue by Namanbhatia7** [Namanbhatia7/False9#23]
Create a route to live matches with help of API used in project to display live matches.

**Comment by puffdebu** [comment]
Hi, I wish to contribute to this.

**Comment by Namanbhatia7** [comment]
Hey @puffdebu , Sure I will assign it to you. Also, are you participating in KWoC'20. If yes, Please join Slack channel for all project related communication. Here is the [link](https://join.slack.com/t/false9-kwoc/shared_invite/zt-jm0d4rfq-i9kK49pwh4e296t6WmLfiQ)

**Comment by devartstar** [comment]
I want to work on this issue.
