### ISSUE TITLE
create a nav-bar

### ISSUE THREAD

**Issue by Namanbhatia7** [Namanbhatia7/False9#25]
Create a navbar such that it become transparent on scrolling.

**Comment by iamkrati22** [comment]
@Namanbhatia7 I would like to work on this issue

**Comment by Namanbhatia7** [comment]
Go ahead @iamkrati22 . I am assigning this issue to you. Also are you a Participant of KWoC'20? if yes, then please join Slack communication channel for this project.
 [click here]( false9-kwoc.slack.com) to join the channel :)

**Comment by Harshit850** [comment]
@Namanbhatia7 Can i work on this issue?

**Comment by NikhilSharmaWe** [comment]
looking forward to contribute but tell which links to be included in the nav bar
