### ISSUE TITLE
Add a Footer

### ISSUE THREAD

**Issue by Namanbhatia7** [Namanbhatia7/False9#26]
Create a footer that matches the current site theme and cover following points:
* Dynamic Copyright
* Made with help of [football-data.org](https://www.football-data.org/)

**Comment by chiteshbansal** [comment]
I am interested in this issue and would like to work on it

**Comment by Namanbhatia7** [comment]
@chiteshbansal Sure! Please attach a Screenshot of footer along with the PR you will make

**Comment by NikhilSharmaWe** [comment]
I am intrested in this issue looking forward to contribute
