### ISSUE TITLE
Responsive Cards in League and Competition Page

### ISSUE THREAD

**Issue by Namanbhatia7** [Namanbhatia7/False9#5]
Make Cards compatible to mobile in league and Competition Page.

**Comment by riyakalra** [comment]
Please assign this issue to me.

**Comment by ayushi-1408** [comment]
I would love to work on this issue

**Comment by ayushbasak** [comment]
Would you explain what do you mean by *compatible to mobile*?

**Comment by Namanbhatia7** [comment]
Hey @ayushbasak @ayushi-1408  thanks for your interest but this issue has been resolved.
I am opening more issues that might interest you 
Thankyou :)
